apiVersion: v1
kind: ConfigMap
metadata:
    name: app-config
    namespace: dcim
data:
    NODE_ENV: "production"
    AUTH_URL: "http://localhost:30300"
    TIMESCALEDB_ENABLED: "true"
    NEXT_TELEMETRY_DISABLED: "1"
