apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: dcim
type: Opaque
stringData:
    # Change these values before deploying to non-local environments
    POSTGRES_DB: dcim
    POSTGRES_USER: dcim
    POSTGRES_PASSWORD: dcim_k8s_password
