apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: {{ include "dcim.namespace" . }}
    labels:
        {{- include "dcim.labels" . | nindent 8 }}
        app.kubernetes.io/component: postgres
type: Opaque
data:
    POSTGRES_DB: {{ .Values.postgres.credentials.database | b64enc | quote }}
    POSTGRES_USER: {{ .Values.postgres.credentials.username | b64enc | quote }}
    POSTGRES_PASSWORD: {{ .Values.postgres.credentials.password | b64enc | quote }}
