apiVersion: v1
kind: Secret
metadata:
    name: go-service-secret
    namespace: {{ include "dcim.namespace" . }}
    labels:
        {{- include "dcim.labels" . | nindent 8 }}
        app.kubernetes.io/component: go-service
type: Opaque
data:
    DATABASE_URL: {{ include "dcim.databaseUrl" . | b64enc | quote }}
    INTERNAL_SECRET: {{ .Values.goService.secrets.INTERNAL_SECRET | b64enc | quote }}
