apiVersion: v1
kind: Service
metadata:
    name: dcim-go-service
    namespace: {{ include "dcim.namespace" . }}
    labels:
        {{- include "dcim.labels" . | nindent 8 }}
        app.kubernetes.io/component: go-service
spec:
    type: ClusterIP
    selector:
        {{- include "dcim.goService.selectorLabels" . | nindent 8 }}
    ports:
        - port: {{ .Values.goService.service.port }}
          targetPort: http
          name: http
